language: java
sudo: false
dist: trusty
services: mongodb
before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
  - env: JDK='Oracle JDK 10'
    install: ". ./install-jdk.sh -F 10 -L BCL"
env:
  global:
  - secure: a/6/tEXq5uh0wraiFuINAEvcwbYWJtxwp0/T1Ia4X2vuYVr/r8K9vs3J0lCcMjwwasqtQEVwcgSCVjtEHgdvv0yejgl8h/7TLzsjVUDq1+IN2mfC/H/+9RKhkfGcbvZC30GSRBYpKgoXCvwPQJZgzAqHTbV0THek8qmKRbPSE1V6/D+vzE7ep52MPmV40A6hyubgP0T8FFb0wkBxCpMuEg4ZVh7l9KOPqKWhWbmgFKSHYKSTp9rGywZP9GhDpguPKyRraRjpVkT4pkiJQuhuHp2XuLB499IKxmtdNwBrlBLzalBZ5HNVSYTgSB2jMta4ijwe25+F5ZgOleEBvgVq35J3ZfdX3J+71jKIqRHwtuG27S8rLwcq+cbpuUBIaMo58nanix6b1R1j66eGePup6DGKVQOLp2Qh4/p0YmWOxANKT0qs5U6WnjkucpePDk5XADzGo+SMtujWIogQ2X2KQ/9xcBOyV0TyvSJdmVGOAoe5bvpRcyTYuhetG1vPBB0NGouxQ2w7+7EeLq3KIIsgZI81tcKiAG3MsA6S2RFvwu5HgTWJG60rruOOEzeqeKrBeRCRe30QhCxoKpO97qijE0spFBq0XBkDxYPpnUAWC1DQHYfP6OpyBhUlCcx3DEmVbX4hpRF3gZy7dV9+0ogBI/oIfnE1AVOt/T4yi8/ap8s=
  - secure: aExNVBJiIA9P2LIqBfJpVaZF1b7W71AV3WdI0bj7Ra769/sRS9vuHEtlTEJNfQ9XfB8gZx7b7ONdOh48aA5a89HoqZmrFgM7w1wAqTS8TRUFcK8OCgPLTlqnDuqQMuxOHJeu/hQpS+8SmxsEhybgRWiIrFlpWEPG5I75onrRw4ZpLf5t6KXPK/01FlUI33E+oAPWWrnuKoRzTeaO0ZFCcQaWf+bwByC4a4c+HpUDlKmtDP+4E88wXnuiBKsIxAECR6ohdw5PJrLV2QoLuUtM2DytoJ9ksnMjvWrBzwQScCrZaM9Xi9DQ3JWucMK5H1UsZm4TfbxX92rV93QGpArG0XlFYA/gr9Yecc6J5lwySRq1Fmi/cTaCUz/zX+gR5/s6qg0E/sb1OIwIUgmBy7KkoNASVTpY/0R3CLXfR3g+KgCcvP7CGI6qBQrNcEUxTyTzAMKPgBAM8lVEACc546SHPPWXHsxLSCD+Z/76FbbLApZX5ZpTQ4Ok9SOIvrMgm/ZeTSDa4yS+81jKAvQTRFUSPkjbqTsQdsHlG8A1xveQSZ8bodQoPV/MLsDsrjpPyQlt1lNdTWYS+3Rzi0iFIMHYZdHtKr0X78attXByAFGDhtUU/fngpntacQ6edaN+VKRNhzA/c3VeNTzCBNe4P6oqqRG8fzI9Wba/CEUxV82dIQ0=
after_success:
- bash <(curl -s https://codecov.io/bash)
- "./gradlew assemble"
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- set +e
- export REPO=aista/general-type-service
- docker build -t $REPO:$TRAVIS_TAG -t $REPO:latest .
- docker push $REPO