spring:
  application:
    name: generaltypeservice
spring:
  data:
    mongodb:
      uri: mongodb://localhost/general_type_service # Mongo database URI. When set, host and port are ignored.
      port: 27017 # Mongo server port.
      enabled: true # Enable Mongo repositories.
      username: user # Login user of the mongo server.
      password: pass # Login password of the mongo server.
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: false
    fetch-registry: false