spring:
  application:
    name: generaltypeservice
  data:
    mongodb:
      uri: mongodb://localhost/general_type_service # Mongo database URI. When set, host and port are ignored.
      port: 27017 # Mongo server port.
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false